SKILLS_DB = [
    "python",
    "django",
    "fastapi",
    "flask",
    "machine learning",
    "deep learning",
    "numpy",
    "pandas",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "mongodb",
    "mysql",
    "postgresql",
    "react",
    "node",
    "express",
    "docker",
    "aws",
    "git",
    "html",
    "css",
    "javascript"
]